Update deploy-to-eks.yml

diff --git a/.github/workflows/deploy-to-eks.yml b/.github/workflows/deploy-to-eks.yml
--- a/.github/workflows/deploy-to-eks.yml
+++ b/.github/workflows/deploy-to-eks.yml
@@ -25,6 +25,7 @@ jobs:
   deploy-to-eks:
     name: 'Deploy Applications to EKS Cluster'
     runs-on: ubuntu-latest
+    
     outputs:
       lb_dns: ${{ steps.get_dns_name.outputs.lb_dns }}
     steps:
@@ -61,7 +62,27 @@ jobs:
       - name: Verify Metrics Server
         run: |
           kubectl get deployment metrics-server -n kube-system
-          
+
+
+      # Run Trivy Scan on the Docker Image 
+
+      - name: Build Docker Image
+        working-directory: ./.github/workflows/../.././infrastructure/k8s/
+        run: |
+         IMAGE_TAG=$(git rev-parse --short HEAD)
+         docker build -t my-image:${IMAGE_TAG} .
+
+      - name: Scan Docker Image with Trivy
+        uses: aquasecurity/trivy-action@master
+        with:
+         image-ref: 'my-image:${git rev-parse --short HEAD}'
+         format: 'table'  # Optional: output format (table, json, sarif)
+         #exit-code: '1'   # Optional: fail the build if vulnerabilities are found
+         severity: 'CRITICAL,HIGH'  # Optional: specify severity levels
+         ignore-unfixed: true
+         vuln-type: 'os,library'
+
+         
       - name: Log in to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
@@ -80,17 +101,17 @@ jobs:
 
       - name: Initiate ECR Image Scan
         run: |
-         aws ecr start-image-scan --repository-name ${ECR_REGISTRY}/${ECR_REPO}  --image-id imageTag=${IMAGE_TAG}
+         aws ecr start-image-scan --repository-name ${ECR_REPO}  --image-id imageTag=${IMAGE_TAG}
 
       - name: Wait for Scan to Complete
         run: |
-         aws ecr wait image-scan-complete  --repository-name ${ECR_REGISTRY}/${ECR_REPO}  --image-id imageTag=${IMAGE_TAG}
+         aws ecr wait image-scan-complete  --repository-name ${ECR_REPO}  --image-id imageTag=${IMAGE_TAG}
 
       - name: Get ECR Scan Results
   
         run: |
          aws ecr describe-image-scan-findings \
-         --repository-name ${ECR_REGISTRY}/${ECR_REPO} \
+         --repository-name ${ECR_REPO} \
          --image-id imageTag=${IMAGE_TAG}  > scan_results.json
          cat scan_results.json
 
@@ -102,7 +123,7 @@ jobs:
          echo "High vulnerabilities: $HIGH_COUNT"
          if [ "$CRITICAL_COUNT" -gt 0 ] || [ "$HIGH_COUNT" -gt 0 ]; then
           echo "Security scan failed due to critical or high vulnerabilities."
-      
+          # exit 1 if in production, for demo purpose, it can proceed to next 
          else
           echo "No critical or high vulnerabilities found."
          fi
